import 'dart:convert';
/// result : [{"ID":"30751","TITLE":"P T PHOTOGRAPHY","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"0","CONTACT_ID":"1253","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":"CALL","SOURCE_DESCRIPTION":null,"STATUS_ID":"CONVERTED","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"N","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"31","CREATED_BY_ID":"31","MODIFY_BY_ID":"7","DATE_CREATE":"2022-01-18T11:05:07+03:00","DATE_MODIFY":"2022-02-21T09:45:30+03:00","DATE_CLOSED":"2022-01-19T09:41:08+03:00","STATUS_SEMANTIC_ID":"S","OPENED":"Y","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"7","MOVED_TIME":"2022-01-19T09:41:08+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"30759","TITLE":"Nitin Arora","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"11155","CONTACT_ID":"1259","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":"CALL","SOURCE_DESCRIPTION":null,"STATUS_ID":"CONVERTED","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"N","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"5","CREATED_BY_ID":"5","MODIFY_BY_ID":"5","DATE_CREATE":"2022-01-19T21:00:46+03:00","DATE_MODIFY":"2022-01-19T21:05:52+03:00","DATE_CLOSED":"2022-01-19T21:05:52+03:00","STATUS_SEMANTIC_ID":"S","OPENED":"Y","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"5","MOVED_TIME":"2022-01-19T21:05:52+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36227","TITLE":"Nishant","HONORIFIC":null,"NAME":"Nishant","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"13159","CONTACT_ID":"1981","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:51+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-05T15:46:06+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36229","TITLE":"Sushmita","HONORIFIC":null,"NAME":"Sushmita","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12515","CONTACT_ID":"1979","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-07T12:05:43+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36231","TITLE":"Amen Photgraphy","HONORIFIC":null,"NAME":"Shaul","SECOND_NAME":null,"LAST_NAME":"Jyotsana Gaikward","COMPANY_TITLE":null,"COMPANY_ID":"12513","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"PROCESSED","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"7","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-11-08T00:38:24+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"65","MOVED_TIME":"2022-02-25T15:30:58+03:00","ADDRESS":"Madhya Pradesh","ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":"75","UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36233","TITLE":"Lensking","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12511","CONTACT_ID":"1977","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-26T15:15:51+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36235","TITLE":"Ravindra","HONORIFIC":null,"NAME":"Ravindra","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12509","CONTACT_ID":"1975","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-07T12:20:08+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36237","TITLE":"Mahadev","HONORIFIC":null,"NAME":"Mahadev","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12507","CONTACT_ID":"1973","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-07T13:03:03+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36239","TITLE":"Sayan Kumar","HONORIFIC":null,"NAME":"Sayan","SECOND_NAME":null,"LAST_NAME":"Kumar","COMPANY_TITLE":null,"COMPANY_ID":"12505","CONTACT_ID":"1971","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-07T13:04:47+03:00","ADDRESS":"Alipurduar, West Bengal","ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":"77","UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36241","TITLE":"XUZ company","HONORIFIC":null,"NAME":"Manmeet","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12503","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-07T13:09:18+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36243","TITLE":"Aamuliah Qazi Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12501","CONTACT_ID":"1969","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-07T13:18:00+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36245","TITLE":"Keval Premi Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12499","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-08-13T10:42:43+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36247","TITLE":"Kushwaha Dharmendra Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12497","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T16:38:36+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36249","TITLE":"Lovemeet Virk Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12495","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-09T10:55:33+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36251","TITLE":"Harish Gahlawat Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12493","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T16:28:11+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36253","TITLE":"Kailash Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12491","CONTACT_ID":"1967","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T16:21:47+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36255","TITLE":"Raam Hockey Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12489","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T16:10:54+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36257","TITLE":"Flash ST Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12487","CONTACT_ID":null,"IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T16:04:20+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36259","TITLE":"A One Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"12485","CONTACT_ID":"1965","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T15:53:58+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36261","TITLE":"Firduaz Raza Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:40+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"249","MOVED_TIME":"2022-08-08T17:54:11+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36263","TITLE":"Kalyan Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"249","MOVED_TIME":"2022-08-08T17:50:03+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36265","TITLE":"Manoj Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_DXKGIZ","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"85","MOVED_TIME":"2022-04-28T15:55:33+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36267","TITLE":"Rahul Chauhan Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-03T15:50:25+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36269","TITLE":"Rahul Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-07-15T13:24:14+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36271","TITLE":"Vipul Tailor Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-16T15:38:37+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36273","TITLE":"Sonu Arts Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":"0","CONTACT_ID":"2785","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T15:13:59+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36275","TITLE":"Sameer Singhaniya Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T16:24:05+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36277","TITLE":"Sajal Poddar Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T14:49:41+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36279","TITLE":"Sapa Rakesh Kumar Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_DXKGIZ","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T14:46:41+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36281","TITLE":"Aman Agarwal Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T14:37:19+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36285","TITLE":"Sai Photography","HONORIFIC":null,"NAME":"Sachin","SECOND_NAME":null,"LAST_NAME":"Photography","COMPANY_TITLE":null,"COMPANY_ID":"14047","CONTACT_ID":"2777","IS_RETURN_CUSTOMER":"Y","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:52+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T14:22:47+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36287","TITLE":"Raju reddy","HONORIFIC":null,"NAME":"Raju","SECOND_NAME":null,"LAST_NAME":"reddy","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T14:07:03+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36289","TITLE":"Friends digital studio & photography","HONORIFIC":null,"NAME":"Ram","SECOND_NAME":null,"LAST_NAME":"nyp","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"243","MOVED_TIME":"2022-05-03T14:03:02+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36291","TITLE":"Balu","HONORIFIC":null,"NAME":"Balu","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_DXKGIZ","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"85","MOVED_TIME":"2022-04-07T10:57:51+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36293","TITLE":"Pradeep Chulaki","HONORIFIC":null,"NAME":"Pradeep","SECOND_NAME":null,"LAST_NAME":"Chulaki","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:41+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-26T15:25:46+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36295","TITLE":"Grand moment photography","HONORIFIC":null,"NAME":"Siva","SECOND_NAME":null,"LAST_NAME":"kumar","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_DXKGIZ","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"85","MOVED_TIME":"2022-04-07T10:47:23+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36297","TITLE":"Ansh Digital Studio","HONORIFIC":null,"NAME":"Manoj","SECOND_NAME":null,"LAST_NAME":"Kumar","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-06T12:52:47+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36299","TITLE":"Avi suvamkar","HONORIFIC":null,"NAME":"Avi","SECOND_NAME":null,"LAST_NAME":"suvamkar","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T15:45:01+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36301","TITLE":"Rishab osho","HONORIFIC":null,"NAME":"Rishab","SECOND_NAME":null,"LAST_NAME":"osho","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T15:22:50+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36303","TITLE":"LM pappu","HONORIFIC":null,"NAME":"LM","SECOND_NAME":null,"LAST_NAME":"pappu","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T15:20:35+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36305","TITLE":"Mandeep","HONORIFIC":null,"NAME":"Mandeep","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T15:07:20+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36307","TITLE":"Saurabh","HONORIFIC":null,"NAME":"Saurabh","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-06T08:39:04+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36309","TITLE":"Chandra Shekhar sahoo","HONORIFIC":null,"NAME":"Chandra","SECOND_NAME":null,"LAST_NAME":"Shekhar sahoo","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T16:02:43+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36311","TITLE":"Dhiraj","HONORIFIC":null,"NAME":"Dhiraj","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"Y","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T15:56:37+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36313","TITLE":"SR photography","HONORIFIC":null,"NAME":"Chandu","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T15:39:27+03:00","ADDRESS":"Siddipet","ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":"79","UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36315","TITLE":"Deepak Saini","HONORIFIC":null,"NAME":"Deepak","SECOND_NAME":null,"LAST_NAME":"Saini","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-05T14:48:39+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36317","TITLE":"Astrospeak Photography","HONORIFIC":null,"NAME":null,"SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-04T14:16:46+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36319","TITLE":"Dharmendra kumar","HONORIFIC":null,"NAME":"Dharmendra","SECOND_NAME":null,"LAST_NAME":"kumar","COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"1","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-04T14:12:26+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36321","TITLE":"Gurpreet","HONORIFIC":null,"NAME":"Gurpreet","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_DXKGIZ","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-26T16:16:50+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null},{"ID":"36323","TITLE":"Jagadish","HONORIFIC":null,"NAME":"Jagadish","SECOND_NAME":null,"LAST_NAME":null,"COMPANY_TITLE":null,"COMPANY_ID":null,"CONTACT_ID":null,"IS_RETURN_CUSTOMER":"N","BIRTHDATE":"","SOURCE_ID":null,"SOURCE_DESCRIPTION":null,"STATUS_ID":"UC_D4NXME","STATUS_DESCRIPTION":null,"POST":null,"COMMENTS":null,"CURRENCY_ID":"INR","OPPORTUNITY":"0.00","IS_MANUAL_OPPORTUNITY":"N","HAS_PHONE":"Y","HAS_EMAIL":"N","HAS_IMOL":"N","ASSIGNED_BY_ID":"249","CREATED_BY_ID":"7","MODIFY_BY_ID":"241","DATE_CREATE":"2022-01-21T09:26:42+03:00","DATE_MODIFY":"2022-09-13T08:58:53+03:00","DATE_CLOSED":"","STATUS_SEMANTIC_ID":"P","OPENED":"N","ORIGINATOR_ID":null,"ORIGIN_ID":null,"MOVED_BY_ID":"241","MOVED_TIME":"2022-05-04T13:52:41+03:00","ADDRESS":null,"ADDRESS_2":null,"ADDRESS_CITY":null,"ADDRESS_POSTAL_CODE":null,"ADDRESS_REGION":null,"ADDRESS_PROVINCE":null,"ADDRESS_COUNTRY":null,"ADDRESS_COUNTRY_CODE":null,"ADDRESS_LOC_ADDR_ID":null,"UTM_SOURCE":null,"UTM_MEDIUM":null,"UTM_CAMPAIGN":null,"UTM_CONTENT":null,"UTM_TERM":null}]
/// next : 50
/// total : 4869
/// time : {"start":1669445672.3309121,"finish":1669445672.4748371,"duration":0.14392495155334473,"processing":0.11634707450866699,"date_start":"2022-11-26T09:54:32+03:00","date_finish":"2022-11-26T09:54:32+03:00","operating_reset_at":1669446272,"operating":0}

LeadsModel leadsModelFromJson(String str) => LeadsModel.fromJson(json.decode(str));
String leadsModelToJson(LeadsModel data) => json.encode(data.toJson());
class LeadsModel {
  LeadsModel({
      List<Result>? result, 
      num? next, 
      num? total, 
      Time? time,}){
    _result = result;
    _next = next;
    _total = total;
    _time = time;
}

  LeadsModel.fromJson(dynamic json) {
    if (json['result'] != null) {
      _result = [];
      json['result'].forEach((v) {
        _result?.add(Result.fromJson(v));
      });
    }
    _next = json['next'];
    _total = json['total'];
    _time = json['time'] != null ? Time.fromJson(json['time']) : null;
  }
  List<Result>? _result;
  num? _next;
  num? _total;
  Time? _time;
LeadsModel copyWith({  List<Result>? result,
  num? next,
  num? total,
  Time? time,
}) => LeadsModel(  result: result ?? _result,
  next: next ?? _next,
  total: total ?? _total,
  time: time ?? _time,
);
  List<Result>? get result => _result;
  num? get next => _next;
  num? get total => _total;
  Time? get time => _time;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (_result != null) {
      map['result'] = _result?.map((v) => v.toJson()).toList();
    }
    map['next'] = _next;
    map['total'] = _total;
    if (_time != null) {
      map['time'] = _time?.toJson();
    }
    return map;
  }

}

/// start : 1669445672.3309121
/// finish : 1669445672.4748371
/// duration : 0.14392495155334473
/// processing : 0.11634707450866699
/// date_start : "2022-11-26T09:54:32+03:00"
/// date_finish : "2022-11-26T09:54:32+03:00"
/// operating_reset_at : 1669446272
/// operating : 0

Time timeFromJson(String str) => Time.fromJson(json.decode(str));
String timeToJson(Time data) => json.encode(data.toJson());
class Time {
  Time({
      num? start, 
      num? finish, 
      num? duration, 
      num? processing, 
      String? dateStart, 
      String? dateFinish, 
      num? operatingResetAt, 
      num? operating,}){
    _start = start;
    _finish = finish;
    _duration = duration;
    _processing = processing;
    _dateStart = dateStart;
    _dateFinish = dateFinish;
    _operatingResetAt = operatingResetAt;
    _operating = operating;
}

  Time.fromJson(dynamic json) {
    _start = json['start'];
    _finish = json['finish'];
    _duration = json['duration'];
    _processing = json['processing'];
    _dateStart = json['date_start'];
    _dateFinish = json['date_finish'];
    _operatingResetAt = json['operating_reset_at'];
    _operating = json['operating'];
  }
  num? _start;
  num? _finish;
  num? _duration;
  num? _processing;
  String? _dateStart;
  String? _dateFinish;
  num? _operatingResetAt;
  num? _operating;
Time copyWith({  num? start,
  num? finish,
  num? duration,
  num? processing,
  String? dateStart,
  String? dateFinish,
  num? operatingResetAt,
  num? operating,
}) => Time(  start: start ?? _start,
  finish: finish ?? _finish,
  duration: duration ?? _duration,
  processing: processing ?? _processing,
  dateStart: dateStart ?? _dateStart,
  dateFinish: dateFinish ?? _dateFinish,
  operatingResetAt: operatingResetAt ?? _operatingResetAt,
  operating: operating ?? _operating,
);
  num? get start => _start;
  num? get finish => _finish;
  num? get duration => _duration;
  num? get processing => _processing;
  String? get dateStart => _dateStart;
  String? get dateFinish => _dateFinish;
  num? get operatingResetAt => _operatingResetAt;
  num? get operating => _operating;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['start'] = _start;
    map['finish'] = _finish;
    map['duration'] = _duration;
    map['processing'] = _processing;
    map['date_start'] = _dateStart;
    map['date_finish'] = _dateFinish;
    map['operating_reset_at'] = _operatingResetAt;
    map['operating'] = _operating;
    return map;
  }

}

/// ID : "30751"
/// TITLE : "P T PHOTOGRAPHY"
/// HONORIFIC : null
/// NAME : null
/// SECOND_NAME : null
/// LAST_NAME : null
/// COMPANY_TITLE : null
/// COMPANY_ID : "0"
/// CONTACT_ID : "1253"
/// IS_RETURN_CUSTOMER : "Y"
/// BIRTHDATE : ""
/// SOURCE_ID : "CALL"
/// SOURCE_DESCRIPTION : null
/// STATUS_ID : "CONVERTED"
/// STATUS_DESCRIPTION : null
/// POST : null
/// COMMENTS : null
/// CURRENCY_ID : "INR"
/// OPPORTUNITY : "0.00"
/// IS_MANUAL_OPPORTUNITY : "N"
/// HAS_PHONE : "N"
/// HAS_EMAIL : "N"
/// HAS_IMOL : "N"
/// ASSIGNED_BY_ID : "31"
/// CREATED_BY_ID : "31"
/// MODIFY_BY_ID : "7"
/// DATE_CREATE : "2022-01-18T11:05:07+03:00"
/// DATE_MODIFY : "2022-02-21T09:45:30+03:00"
/// DATE_CLOSED : "2022-01-19T09:41:08+03:00"
/// STATUS_SEMANTIC_ID : "S"
/// OPENED : "Y"
/// ORIGINATOR_ID : null
/// ORIGIN_ID : null
/// MOVED_BY_ID : "7"
/// MOVED_TIME : "2022-01-19T09:41:08+03:00"
/// ADDRESS : null
/// ADDRESS_2 : null
/// ADDRESS_CITY : null
/// ADDRESS_POSTAL_CODE : null
/// ADDRESS_REGION : null
/// ADDRESS_PROVINCE : null
/// ADDRESS_COUNTRY : null
/// ADDRESS_COUNTRY_CODE : null
/// ADDRESS_LOC_ADDR_ID : null
/// UTM_SOURCE : null
/// UTM_MEDIUM : null
/// UTM_CAMPAIGN : null
/// UTM_CONTENT : null
/// UTM_TERM : null

Result resultFromJson(String str) => Result.fromJson(json.decode(str));
String resultToJson(Result data) => json.encode(data.toJson());
class Result {
  Result({
      String? id, 
      String? title, 
      dynamic honorific, 
      dynamic name, 
      dynamic secondname, 
      dynamic lastname, 
      dynamic companytitle, 
      String? companyid, 
      String? contactid, 
      String? isreturncustomer, 
      String? birthdate, 
      String? sourceid, 
      dynamic sourcedescription, 
      String? statusid, 
      dynamic statusdescription, 
      dynamic post, 
      dynamic comments, 
      String? currencyid, 
      String? opportunity, 
      String? ismanualopportunity, 
      String? hasphone, 
      String? hasemail, 
      String? hasimol, 
      String? assignedbyid, 
      String? createdbyid, 
      String? modifybyid, 
      String? datecreate, 
      String? datemodify, 
      String? dateclosed, 
      String? statussemanticid, 
      String? opened, 
      dynamic originatorid, 
      dynamic originid, 
      String? movedbyid, 
      String? movedtime, 
      dynamic address, 
      dynamic address2, 
      dynamic addresscity, 
      dynamic addresspostalcode, 
      dynamic addressregion, 
      dynamic addressprovince, 
      dynamic addresscountry, 
      dynamic addresscountrycode, 
      dynamic addresslocaddrid, 
      dynamic utmsource, 
      dynamic utmmedium, 
      dynamic utmcampaign, 
      dynamic utmcontent, 
      dynamic utmterm,}){
    _id = id;
    _title = title;
    _honorific = honorific;
    _name = name;
    _secondname = secondname;
    _lastname = lastname;
    _companytitle = companytitle;
    _companyid = companyid;
    _contactid = contactid;
    _isreturncustomer = isreturncustomer;
    _birthdate = birthdate;
    _sourceid = sourceid;
    _sourcedescription = sourcedescription;
    _statusid = statusid;
    _statusdescription = statusdescription;
    _post = post;
    _comments = comments;
    _currencyid = currencyid;
    _opportunity = opportunity;
    _ismanualopportunity = ismanualopportunity;
    _hasphone = hasphone;
    _hasemail = hasemail;
    _hasimol = hasimol;
    _assignedbyid = assignedbyid;
    _createdbyid = createdbyid;
    _modifybyid = modifybyid;
    _datecreate = datecreate;
    _datemodify = datemodify;
    _dateclosed = dateclosed;
    _statussemanticid = statussemanticid;
    _opened = opened;
    _originatorid = originatorid;
    _originid = originid;
    _movedbyid = movedbyid;
    _movedtime = movedtime;
    _address = address;
    _address2 = address2;
    _addresscity = addresscity;
    _addresspostalcode = addresspostalcode;
    _addressregion = addressregion;
    _addressprovince = addressprovince;
    _addresscountry = addresscountry;
    _addresscountrycode = addresscountrycode;
    _addresslocaddrid = addresslocaddrid;
    _utmsource = utmsource;
    _utmmedium = utmmedium;
    _utmcampaign = utmcampaign;
    _utmcontent = utmcontent;
    _utmterm = utmterm;
}

  Result.fromJson(dynamic json) {
    _id = json['ID'];
    _title = json['TITLE'];
    _honorific = json['HONORIFIC'];
    _name = json['NAME'];
    _secondname = json['SECOND_NAME'];
    _lastname = json['LAST_NAME'];
    _companytitle = json['COMPANY_TITLE'];
    _companyid = json['COMPANY_ID'];
    _contactid = json['CONTACT_ID'];
    _isreturncustomer = json['IS_RETURN_CUSTOMER'];
    _birthdate = json['BIRTHDATE'];
    _sourceid = json['SOURCE_ID'];
    _sourcedescription = json['SOURCE_DESCRIPTION'];
    _statusid = json['STATUS_ID'];
    _statusdescription = json['STATUS_DESCRIPTION'];
    _post = json['POST'];
    _comments = json['COMMENTS'];
    _currencyid = json['CURRENCY_ID'];
    _opportunity = json['OPPORTUNITY'];
    _ismanualopportunity = json['IS_MANUAL_OPPORTUNITY'];
    _hasphone = json['HAS_PHONE'];
    _hasemail = json['HAS_EMAIL'];
    _hasimol = json['HAS_IMOL'];
    _assignedbyid = json['ASSIGNED_BY_ID'];
    _createdbyid = json['CREATED_BY_ID'];
    _modifybyid = json['MODIFY_BY_ID'];
    _datecreate = json['DATE_CREATE'];
    _datemodify = json['DATE_MODIFY'];
    _dateclosed = json['DATE_CLOSED'];
    _statussemanticid = json['STATUS_SEMANTIC_ID'];
    _opened = json['OPENED'];
    _originatorid = json['ORIGINATOR_ID'];
    _originid = json['ORIGIN_ID'];
    _movedbyid = json['MOVED_BY_ID'];
    _movedtime = json['MOVED_TIME'];
    _address = json['ADDRESS'];
    _address2 = json['ADDRESS_2'];
    _addresscity = json['ADDRESS_CITY'];
    _addresspostalcode = json['ADDRESS_POSTAL_CODE'];
    _addressregion = json['ADDRESS_REGION'];
    _addressprovince = json['ADDRESS_PROVINCE'];
    _addresscountry = json['ADDRESS_COUNTRY'];
    _addresscountrycode = json['ADDRESS_COUNTRY_CODE'];
    _addresslocaddrid = json['ADDRESS_LOC_ADDR_ID'];
    _utmsource = json['UTM_SOURCE'];
    _utmmedium = json['UTM_MEDIUM'];
    _utmcampaign = json['UTM_CAMPAIGN'];
    _utmcontent = json['UTM_CONTENT'];
    _utmterm = json['UTM_TERM'];
  }
  String? _id;
  String? _title;
  dynamic _honorific;
  dynamic _name;
  dynamic _secondname;
  dynamic _lastname;
  dynamic _companytitle;
  String? _companyid;
  String? _contactid;
  String? _isreturncustomer;
  String? _birthdate;
  String? _sourceid;
  dynamic _sourcedescription;
  String? _statusid;
  dynamic _statusdescription;
  dynamic _post;
  dynamic _comments;
  String? _currencyid;
  String? _opportunity;
  String? _ismanualopportunity;
  String? _hasphone;
  String? _hasemail;
  String? _hasimol;
  String? _assignedbyid;
  String? _createdbyid;
  String? _modifybyid;
  String? _datecreate;
  String? _datemodify;
  String? _dateclosed;
  String? _statussemanticid;
  String? _opened;
  dynamic _originatorid;
  dynamic _originid;
  String? _movedbyid;
  String? _movedtime;
  dynamic _address;
  dynamic _address2;
  dynamic _addresscity;
  dynamic _addresspostalcode;
  dynamic _addressregion;
  dynamic _addressprovince;
  dynamic _addresscountry;
  dynamic _addresscountrycode;
  dynamic _addresslocaddrid;
  dynamic _utmsource;
  dynamic _utmmedium;
  dynamic _utmcampaign;
  dynamic _utmcontent;
  dynamic _utmterm;
Result copyWith({  String? id,
  String? title,
  dynamic honorific,
  dynamic name,
  dynamic secondname,
  dynamic lastname,
  dynamic companytitle,
  String? companyid,
  String? contactid,
  String? isreturncustomer,
  String? birthdate,
  String? sourceid,
  dynamic sourcedescription,
  String? statusid,
  dynamic statusdescription,
  dynamic post,
  dynamic comments,
  String? currencyid,
  String? opportunity,
  String? ismanualopportunity,
  String? hasphone,
  String? hasemail,
  String? hasimol,
  String? assignedbyid,
  String? createdbyid,
  String? modifybyid,
  String? datecreate,
  String? datemodify,
  String? dateclosed,
  String? statussemanticid,
  String? opened,
  dynamic originatorid,
  dynamic originid,
  String? movedbyid,
  String? movedtime,
  dynamic address,
  dynamic address2,
  dynamic addresscity,
  dynamic addresspostalcode,
  dynamic addressregion,
  dynamic addressprovince,
  dynamic addresscountry,
  dynamic addresscountrycode,
  dynamic addresslocaddrid,
  dynamic utmsource,
  dynamic utmmedium,
  dynamic utmcampaign,
  dynamic utmcontent,
  dynamic utmterm,
}) => Result(  id: id ?? _id,
  title: title ?? _title,
  honorific: honorific ?? _honorific,
  name: name ?? _name,
  secondname: secondname ?? _secondname,
  lastname: lastname ?? _lastname,
  companytitle: companytitle ?? _companytitle,
  companyid: companyid ?? _companyid,
  contactid: contactid ?? _contactid,
  isreturncustomer: isreturncustomer ?? _isreturncustomer,
  birthdate: birthdate ?? _birthdate,
  sourceid: sourceid ?? _sourceid,
  sourcedescription: sourcedescription ?? _sourcedescription,
  statusid: statusid ?? _statusid,
  statusdescription: statusdescription ?? _statusdescription,
  post: post ?? _post,
  comments: comments ?? _comments,
  currencyid: currencyid ?? _currencyid,
  opportunity: opportunity ?? _opportunity,
  ismanualopportunity: ismanualopportunity ?? _ismanualopportunity,
  hasphone: hasphone ?? _hasphone,
  hasemail: hasemail ?? _hasemail,
  hasimol: hasimol ?? _hasimol,
  assignedbyid: assignedbyid ?? _assignedbyid,
  createdbyid: createdbyid ?? _createdbyid,
  modifybyid: modifybyid ?? _modifybyid,
  datecreate: datecreate ?? _datecreate,
  datemodify: datemodify ?? _datemodify,
  dateclosed: dateclosed ?? _dateclosed,
  statussemanticid: statussemanticid ?? _statussemanticid,
  opened: opened ?? _opened,
  originatorid: originatorid ?? _originatorid,
  originid: originid ?? _originid,
  movedbyid: movedbyid ?? _movedbyid,
  movedtime: movedtime ?? _movedtime,
  address: address ?? _address,
  address2: address2 ?? _address2,
  addresscity: addresscity ?? _addresscity,
  addresspostalcode: addresspostalcode ?? _addresspostalcode,
  addressregion: addressregion ?? _addressregion,
  addressprovince: addressprovince ?? _addressprovince,
  addresscountry: addresscountry ?? _addresscountry,
  addresscountrycode: addresscountrycode ?? _addresscountrycode,
  addresslocaddrid: addresslocaddrid ?? _addresslocaddrid,
  utmsource: utmsource ?? _utmsource,
  utmmedium: utmmedium ?? _utmmedium,
  utmcampaign: utmcampaign ?? _utmcampaign,
  utmcontent: utmcontent ?? _utmcontent,
  utmterm: utmterm ?? _utmterm,
);
  String? get id => _id;
  String? get title => _title;
  dynamic get honorific => _honorific;
  dynamic get name => _name;
  dynamic get secondname => _secondname;
  dynamic get lastname => _lastname;
  dynamic get companytitle => _companytitle;
  String? get companyid => _companyid;
  String? get contactid => _contactid;
  String? get isreturncustomer => _isreturncustomer;
  String? get birthdate => _birthdate;
  String? get sourceid => _sourceid;
  dynamic get sourcedescription => _sourcedescription;
  String? get statusid => _statusid;
  dynamic get statusdescription => _statusdescription;
  dynamic get post => _post;
  dynamic get comments => _comments;
  String? get currencyid => _currencyid;
  String? get opportunity => _opportunity;
  String? get ismanualopportunity => _ismanualopportunity;
  String? get hasphone => _hasphone;
  String? get hasemail => _hasemail;
  String? get hasimol => _hasimol;
  String? get assignedbyid => _assignedbyid;
  String? get createdbyid => _createdbyid;
  String? get modifybyid => _modifybyid;
  String? get datecreate => _datecreate;
  String? get datemodify => _datemodify;
  String? get dateclosed => _dateclosed;
  String? get statussemanticid => _statussemanticid;
  String? get opened => _opened;
  dynamic get originatorid => _originatorid;
  dynamic get originid => _originid;
  String? get movedbyid => _movedbyid;
  String? get movedtime => _movedtime;
  dynamic get address => _address;
  dynamic get address2 => _address2;
  dynamic get addresscity => _addresscity;
  dynamic get addresspostalcode => _addresspostalcode;
  dynamic get addressregion => _addressregion;
  dynamic get addressprovince => _addressprovince;
  dynamic get addresscountry => _addresscountry;
  dynamic get addresscountrycode => _addresscountrycode;
  dynamic get addresslocaddrid => _addresslocaddrid;
  dynamic get utmsource => _utmsource;
  dynamic get utmmedium => _utmmedium;
  dynamic get utmcampaign => _utmcampaign;
  dynamic get utmcontent => _utmcontent;
  dynamic get utmterm => _utmterm;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['ID'] = _id;
    map['TITLE'] = _title;
    map['HONORIFIC'] = _honorific;
    map['NAME'] = _name;
    map['SECOND_NAME'] = _secondname;
    map['LAST_NAME'] = _lastname;
    map['COMPANY_TITLE'] = _companytitle;
    map['COMPANY_ID'] = _companyid;
    map['CONTACT_ID'] = _contactid;
    map['IS_RETURN_CUSTOMER'] = _isreturncustomer;
    map['BIRTHDATE'] = _birthdate;
    map['SOURCE_ID'] = _sourceid;
    map['SOURCE_DESCRIPTION'] = _sourcedescription;
    map['STATUS_ID'] = _statusid;
    map['STATUS_DESCRIPTION'] = _statusdescription;
    map['POST'] = _post;
    map['COMMENTS'] = _comments;
    map['CURRENCY_ID'] = _currencyid;
    map['OPPORTUNITY'] = _opportunity;
    map['IS_MANUAL_OPPORTUNITY'] = _ismanualopportunity;
    map['HAS_PHONE'] = _hasphone;
    map['HAS_EMAIL'] = _hasemail;
    map['HAS_IMOL'] = _hasimol;
    map['ASSIGNED_BY_ID'] = _assignedbyid;
    map['CREATED_BY_ID'] = _createdbyid;
    map['MODIFY_BY_ID'] = _modifybyid;
    map['DATE_CREATE'] = _datecreate;
    map['DATE_MODIFY'] = _datemodify;
    map['DATE_CLOSED'] = _dateclosed;
    map['STATUS_SEMANTIC_ID'] = _statussemanticid;
    map['OPENED'] = _opened;
    map['ORIGINATOR_ID'] = _originatorid;
    map['ORIGIN_ID'] = _originid;
    map['MOVED_BY_ID'] = _movedbyid;
    map['MOVED_TIME'] = _movedtime;
    map['ADDRESS'] = _address;
    map['ADDRESS_2'] = _address2;
    map['ADDRESS_CITY'] = _addresscity;
    map['ADDRESS_POSTAL_CODE'] = _addresspostalcode;
    map['ADDRESS_REGION'] = _addressregion;
    map['ADDRESS_PROVINCE'] = _addressprovince;
    map['ADDRESS_COUNTRY'] = _addresscountry;
    map['ADDRESS_COUNTRY_CODE'] = _addresscountrycode;
    map['ADDRESS_LOC_ADDR_ID'] = _addresslocaddrid;
    map['UTM_SOURCE'] = _utmsource;
    map['UTM_MEDIUM'] = _utmmedium;
    map['UTM_CAMPAIGN'] = _utmcampaign;
    map['UTM_CONTENT'] = _utmcontent;
    map['UTM_TERM'] = _utmterm;
    return map;
  }

}