// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWDnLls1q_KrxGgSHxWHa24J80x8XBj8',
    appId: '1:440854636188:web:c67dac53d2297c0a346f59',
    messagingSenderId: '440854636188',
    projectId: 'designoo-84e76',
    authDomain: 'designoo-84e76.firebaseapp.com',
    databaseURL: 'https://designoo-84e76-default-rtdb.firebaseio.com',
    storageBucket: 'designoo-84e76.appspot.com',
    measurementId: 'G-5ZKMWH3CHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWDnLls1q_KrxGgSHxWHa24J80x8XBj8',
    appId: '1:440854636188:android:16f652fa18792dac346f59',
    messagingSenderId: '440854636188',
    projectId: 'designoo-84e76',
    databaseURL: 'https://designoo-84e76-default-rtdb.firebaseio.com',
    storageBucket: 'designoo-84e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1ak_GriGSpN9a_NEEHcLi8seR7JpRlY',
    appId: '1:440854636188:ios:f55de04e89a1f61f346f59',
    messagingSenderId: '440854636188',
    projectId: 'designoo-84e76',
    databaseURL: 'https://designoo-84e76-default-rtdb.firebaseio.com',
    storageBucket: 'designoo-84e76.appspot.com',
    androidClientId: '440854636188-8nrefq3a1i42fu8t2q0bpjftd9c5t5ia.apps.googleusercontent.com',
    iosClientId: '440854636188-lsobidor68gjalc7tapki2rtu5c1u65j.apps.googleusercontent.com',
    iosBundleId: 'com.example.designoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg1ak_GriGSpN9a_NEEHcLi8seR7JpRlY',
    appId: '1:440854636188:ios:f55de04e89a1f61f346f59',
    messagingSenderId: '440854636188',
    projectId: 'designoo-84e76',
    databaseURL: 'https://designoo-84e76-default-rtdb.firebaseio.com',
    storageBucket: 'designoo-84e76.appspot.com',
    androidClientId: '440854636188-8nrefq3a1i42fu8t2q0bpjftd9c5t5ia.apps.googleusercontent.com',
    iosClientId: '440854636188-lsobidor68gjalc7tapki2rtu5c1u65j.apps.googleusercontent.com',
    iosBundleId: 'com.example.designoo',
  );
}
